 (function() {
      
        const fullPdfList = [
            "Chapter 001:01 - Constitution of The Co-operative Republic of Guyana Act",
            "Chapter 001:02 - Republic Act",
            "Chapter 001:03 - Representation of the People Act",
            "Chapter 001:04 - National Assembly (Validity of Elections) Act",
            "Chapter 001:05 - National Assembly (Speaker’s Election and Vacation of Office) Act",
            "Chapter 001:06 - National Assembly (Disqualification) Act",
            "Chapter 001:07 - Ministers, Members of the National Assembly and Special Offices (Emoluments) Act",
            "Chapter 001:08 - Legislative Bodies (Evidence) Act",
            "Chapter 001:09 Representation of the People (Adaption and Modification of Laws) Act",
            "Chapter 001:10 General Elections (Observers) Act",
            "Chapter 002:01 Interpretation and General Clauses Act",
            "Chapter 002:02 Law Revision Act",
            "Chapter 002:03 Statute Law Continuation Act",
            "Chapter 003:01 Court of Appeal Act",
            "Chapter 003:02 High Court Act",
            "Chapter 003:03 Fundamental Rights (Practice and Procedure) Act",
            "Chapter 003:04 Summary Jurisdiction (Appeals) Act",
            "Chapter 003:05 Summary Jurisdiction (Magistrates) Act",
            "Chapter 003:06 Judicial Review Act",
            "Chapter 003:07 Caribbean Court of Justice Act",
            "Chapter 003:08 Caribbean Court of Justice Trust Fund Agreement Act",
            "Chapter 003:09 Protocol to the Agreement Establishing the Caribbean Court of Justice Act",
            "Chapter 003:10 Protocol on the Privileges and Immunities of the Caribbean Court of Justice and the Regional Judicial and Legal Services Commission Act",
            "Chapter 003:11 Protocols to the Agreement Establishing the Caribbean Court of Justice Act",
            "Chapter 003:12 Summary Jurisdiction (Lay Magistrates) Act",
            "Chapter 003:13 Time Limit for Judicial Decisions Act",
            "Chapter 003:14 Recording of Court Proceedings Act",
            "Chapter 004:01 Legal Practitioners Act",
            "Chapter 004:02 Public Notaries Act",
            "Chapter 004:03 Coroners Act",
            "Chapter 004:04 Council of Legal Education Act",
            "Chapter 005:01 Deeds Registry Act",
            "Chapter 005:02 Land Registry Act",
            "Chapter 005:03 Evidence Act",
            "Chapter 005:04 Petitions (Signature) Act",
            "Chapter 005:05 Contempt of Court Act",
            "Chapter 005:06 Land Registry (Validation of Awards) Act",
            "Chapter 005:07 Justices Protection Act",
            "Chapter 005:08 Powers of Attorney Act",
            "Chapter 005:09 Statutory Declarations Act",
            "Chapter 005:10 Evidence (Proceedings in Foreign Tribunals) Act",
            "Chapter 005:11 Deeds Registry Authority Act",
            "Chapter 006:01 Civil Law of Guyana Act",
            "Chapter 006:02 Law Reform (Miscellaneous Provisions) Act",
            "Chapter 006:03 Defamation Act",
            "Chapter 006:04 Debtors Act",
            "Chapter 006:05 State Liability and Proceedings Act",
            "Chapter 007:01 Summary Jurisdiction (Petty Debt) Act",
            "Chapter 007:02 Limitation Act",
            "Chapter 007:03 Arbitration Act",
            "Chapter 007:04 Foreign Judgements (Reciprocal Enforcement) Act",
            "Chapter 007:05 Alternative Resolution Dispute Act",
            "Chapter 008:01 Criminal Law (Offences) Act",
            "Chapter 008:02 Summary Jurisdiction (Offences) Act",
            "Chapter 008:03 Sexual Offences Act",
            "Chapter 008:04 Administration of Justice (Fines) Act",
            "Chapter 009:01 Prevention of Crime Act",
            "Chapter 009:02 Gambling Prevention Act",
            "Chapter 009:03 Cattle Stealing Prevention Act",
            "Chapter 010:01 Criminal Law (Procedure) Act",
            "Chapter 010:02 Summary Jurisdiction (Procedure) Act",
            "Chapter 010:03 Juvenile Offenders Act",
            "Chapter 010:04 Fugitive Offenders Act",
            "Chapter 010:05 Kidnapping Act",
            "Chapter 010:06 Combating of Trafficking in Persons Act",
            "Chapter 010:07 Maritime Drug Trafficking (Suppression) Act",
            "Chapter 010:08 Hijacking and Piracy Act",
            "Chapter 010:09 Criminal Procedure (Plea Bargaining and Plea Agreement) Act",
            "Chapter 010:10 Narcotic Drugs and Psychotropic Substances (control) Act",
            "Chapter 010:11 Anti-Money Laundering and Countering the Financing of Terrorism Act",
            "Chapter 011:01 Prison Act",
            "Chapter 011:02 Extra-Mural Work Act",
            "Chapter 011:03 Whipping and Flogging Act",
            "Chapter 011:04 Probation of Offenders Act",
            "Chapter 011:05 Criminal Law Reform Act",
            "Chapter 011:06 Training Schools Act",
            "Chapter 011:07 Rehabilitation of Offenders Act",
            "Chapter 011:08 Parole Act",
            "Chapter 011:09 Domestic Violence Act",
            "Chapter 012:01 Deceased Persons Estates' Administration Act",
            "Chapter 012:02 Wills Act",
            "Chapter 012:21 Insolvency Act",
            "Chapter 012:22 Official Receiver Act",
            "Chapter 012:23 Deeds of Agreement Act",
            "Chapter 012:24 Family and Dependants Provision Act",
            "Chapter 013:01 Public Trustee Act",
            "Chapter 013:02 Public Institutions (Inmates' Property) Act",
            "Chapter 013:20 De Saffon Trust Act",
            "Chapter 013:21 Patoir Trust Fund Act",
            "Chapter 013:22 Trotman Trust Fund Act",
            "Chapter 013:23 Mitchell Trust Fund Act",
            "Chapter 014:01 Guyana Citizenship Act",
            "Chapter 014:02 Immigration Act",
            "Chapter 014:03 Aliens (Immigration and Registration) Act",
            "Chapter 014:04 Status of Aliens Act",
            "Chapter 014:05 Expulsion of Undesirables Act",
            "Chapter 014:06 Domicile Reform Act",
            "Chapter 015:01 Defence Act",
            "Chapter 015:02 National Service Act",
            "Chapter 015:03 Guyana Defence Force Uniforms Act",
            "Chapter 015:04 Geneva Conventions (Supplementary Provisions) Act",
            "Chapter 015:05 Mutual Assistance in Criminal Matters Act",
            "Chapter 015:06 Security Assistance (CARICOM Member States) Act",
            "Chapter 016:01 Police Act",
            "Chapter 016:03 Public Order Act",
            "Chapter 016:05 Firearms Act",
            "Chapter 016:06 Explosive Act",
            "Chapter 017:01 Police (Discipline) Act",
            "Chapter 017:02 Police Complaints Authority Act",
            "Chapter 018:01 Privileges and Immunities (Diplomatic, Consular and International Organisations) Act",
            "Chapter 018:02 Consular Conventions Act",
            "Chapter 018:03 Caribbean Meteorological Organisation Act",
            "Chapter 018:04 Caribbean Agricultural Research and Development Institute Act",
            "Chapter 018:05 Privileges and Immunities (Commission of the European Communities) Act",
            "Chapter 018:06 Caribbean Community Act",
            "Chapter 018:07 CARICOM Enterprise Regime Act",
            "Chapter 018:07 CARICOM Enterprise Regime Act",
            "Chapter 018:08 Caribbean Community (Free Entry of Skilled Nationals) Act",
            "Chapter 018:09 Caribbean Food Corporation Act",
            "Chapter 018:09 Caribbean Food Corporation Act",
            "Chapter 018:11 Caribbean Community Special Visa Agreement Act",
            "Chapter 019:01 Guyana (Division into Counties) Act",
            "Chapter 019:02 District Government Act",
            "Chapter 019:03 Commission of Inquiry Act",
            "Chapter 019:04 Ombudsman Act",
            "Chapter 019:05 Public Corporations Act",
            "Chapter 019:05 Public Corporations Act",
            "Chapter 019:07 Public Holidays Act",
            "Chapter 019:08 National Registration Act",
            "Chapter 019:09 Statistics Act",
            "Chapter 019:10 Corporate Bodies (Avoidance of Delay in Divestment of Assets) Act",
            "Chapter 020:01 Town and Country Planning Act",
            "Chapter 020:02 Kaieteur National Park Act",
            "Chapter 020:03 National Trust Act",
            "Chapter 020:04 Iwokrama International Centre for Rain Forest Conservation and development Act",
            "Chapter 020:05 Environmental Protection Act",
            "Chapter 020:06 National Parks Commission Act",
            "Chapter 021:01 Publication and Newspapers Act",
            "Chapter 021:02 Cinematograph and Video Act",
            "Chapter 022:01 Fire Prevention Act",
            "Chapter 022:02 Fire Service Act",
            "Chapter 022:03 Fires and Casualties Inquiry Act",
            "Chapter 023:01 Racial Hostility Act",
            "Chapter 023:02 House to House and Public Collections (Control) Act",
            "Chapter 023:03 Music and Dancing Licences Act",
            "Chapter 024:01 Guyana Red Cross Society (Incorporations) Act",
            "Chapter 024:02 Guyana Methodist Trust Corporations Act",
            "Chapter 025:01 National Data Management Authority Act",
            "Chapter 026:01 Integrity Commission Act",
            "Chapter 027:01 Public Service Appellate Tribunal Act",
            "Chapter 027:02 Pensions Act",
            "Chapter 027:03 Pensions (President, Parliament and Special Offices) Act",
            "Chapter 027:04 State Pensions Act",
            "Chapter 027:05 Public Officers' Pensions Act",
            "Chapter 027:06 Promissory Oath Act",
            "Chapter 027:07 Public Officers Spouses Act",
            "Chapter 027:08 Dependants' Pension Act",
            "Chapter 027:09 Guyana National Service (Pensions and Gratuities) Act",
            "Chapter 027:10 Public Officers (Insurance) Act",
            "Chapter 027:11 Constitutional Offices (Remuneration of Holders) Act",
            "Chapter 027:12 Constitution (Prescribed Matters) Act",
            "Chapter 027:13 Pensions (President) Act",
            "Chapter 027:14 Pensions (Holders of Offices in Local Democratic Organs) Act",
            "Chapter 027:15 President Hoyte Pensions Act",
            "Chapter 027:16 Office of the Spouse of the President Act",
            "Chapter 027:17 Former Presidents (Benefits and other Facilities) Act",
            "Chapter 027:18 Leader of the Opposition (Benefits and other Facilities) Act",
            "Chapter 028:01 A Principal Act Municipal and District Councils Act",
            "Chapter 028:02 Local Government Act",
            "Chapter 028:03 Local Authorities (Elections) Act",
            "Chapter 028:04 Valuation for Rating Purposes Act",
            "Chapter 028:05 Local Government (Local Authorities Guarantee Fund) Act",
            "Chapter 028:07 New Amsterdam Town Council (Appraisement) Act",
            "Chapter 028:08 Regional Development Authorities Act",
            "Chapter 028:09 Local Democratic Organs Act",
            "Chapter 028:10 Valuation of Property for Rating Purposes (Validation) Act",
            "Chapter 029:01 Amerindian Act",
            "Chapter 030:01 Water and Sewerage Act",
            "Chapter 032:01 Ministry of Health Act",
            "Chapter 032:02 Medical Practitioners Act",
            "Chapter 032:03 Dental Registration Act",
            "Chapter 032:04 Medex Act",
            "Chapter 032:05 Medical Termination of Pregnancy Act",
            "Chapter 032:06 Regional Health Authorities Act",
            "Chapter 032:07 Pharmacy Practitioners Act",
            "Chapter 033:03 Health Facilities Licensing Act",
            "Chapter 034:02 Antibiotics Act",
            "Chapter 034:03 Food and Drugs Act",
            "Chapter 035:01 Allied Health Professions Act",
            "Chapter 035:02 Public Health (School Children) Immunisation Act",
            "Chapter 035:10 Chest Society (Incorporation) Act",
            "Chapter 036:01 National Insurance and Social Security Act",
            "Chapter 036:02 Poor Relief Act",
            "Chapter 036:03 Old Age Pensions Act",
            "Chapter 036:04 Friendly Societies Act",
            "Chapter 036:05 Persons with Disabilities Act",
            "Chapter 036:20 Housing Act",
            "Chapter 036:21 New Building Society Act",
            "Chapter 036:22 Condominium (Regulation and Miscellaneous Provisions) Act",
            "Chapter 036:23 Rent Restriction Act",
            "Chapter 036:24 Housing Development Act",
            "Chapter 037:01 Ethnic Relations Commission Tribunal Act",
            "Chapter 038:01 Equal Rights Act",
            "Chapter 038:02 Rights Commissions Tribunal Act",
            "Chapter 039:01 Education Act",
            "Chapter 039:02 University of Guyana Act",
            "Chapter 039:03 Government Training College Act",
            "Chapter 039:04 Industrial Training Act",
            "Chapter 039:05 Teachers' Pensions Act",
            "Chapter 039:06 Buxton Scholarship Act",
            "Chapter 039:07 Teaching Service Commission Act",
            "Chapter 039:08 Kuru Kuru Co-operative College Act",
            "Chapter 039:09 Guyana Management Institute Act",
            "Chapter 039:10 National Equivalency Board Act",
            "Chapter 039:11 President's College Act",
            "Chapter 039:12 Caribbean Examination Council Act",
            "Chapter 039:13 Caribbean Examinations Council (Examinations) Act",
            "Chapter 039:14 National Sports Commission Act",
            "Chapter 040:01 National Library Act",
            "Chapter 040:02 Berbice Reading Society Act",
            "Chapter 040:03 National Archives of Guyana Act",
            "Chapter 040:06 Guyana Society Act",
            "Chapter 041:01 Boy Scouts Association Act",
            "Chapter 042:01 National Science Research Council Act",
            "Chapter 043:01 Guyana Free Protestant Episcopal Church Act",
            "Chapter 044: 01 Registration of Births and Deaths Act",
            "Chapter 044:02 Civil Aviation (Birth, Death and Missing Person) Act",
            "Chapter 045:01 Marriage Act",
            "Chapter 045:02 Matrimonial Causes Act",
            "Chapter 045:03 Maintenance Act",
            "Chapter 045:04 Married Persons (Property) Act",
            "Chapter 045:05 Maintenance Orders (Facilities for Enforcement) Act",
            "Chapter 046:01 Infancy Act",
            "Chapter 046:02 Legitimacy Act",
            "Chapter 046:04 Adoption of Children Act",
            "Chapter 046:05 Status of Children Act",
            "Chapter 046:06 Protection of Children Act",
            "Chapter 046:07 Childcare and Protection Agency Act",
            "Chapter 047:01 Post and Telegraph Act",
            "Chapter 047:02 Telecommunications Act",
            "Chapter 047:03 Interception of Communications Act",
            "Chapter 048:01 Common Carriers Act",
            "Chapter 049:01 Guyana Shipping Act",
            "Chapter 049:02 Carriage of Goods by Sea Act",
            "Chapter 049:03 Passengers Act",
            "Chapter 049:04 Transport and Harbours Act",
            "Chapter 049:05 Government Wharves Act",
            "Chapter 049:06 Government and Contract Steamer (Traffic) Act",
            "Chapter 049:07 Shipping Casualties (Investigation and Prevention) Act",
            "Chapter 050:01 River Navigation Act",
            "Chapter 050:02 Demerara River Navigation Markers Act",
            "Chapter 050:03 Demerara Company, Limited, (Sluice) Act",
            "Chapter 050:04 Creeks Act",
            "Chapter 050:05 Boerasirie Creek Act",
            "Chapter 050:06 Hobaboe Creek (Diversion) Act",
            "Chapter 051:01 Roads Act",
            "Chapter 051:02 Motor Vehicles and Road Traffic Act",
            "Chapter 051:03 Motor Vehicles Insurance (Third party Risks) Act",
            "Chapter 051:04 Demerara River (Mackenzie) Bridge Act",
            "Chapter 051:05 Demerara Harbour Bridge Corporation Act",
            "Chapter 051:06 Berbice River Bridge Act",
            "Chapter 052:01 Cheddi Jagan International Airport Act",
            "Chapter 053:01 Civil Aviation Act",
            "Chapter 054:01 Public Utility Undertakings and Public Health Services (Arbitration) Act",
            "Chapter 055:01 Guyana Water Authority Act",
            "Chapter 055:02 Water Commissioners Act",
            "Chapter 055:03 East Demerara Water Conservancy Act",
            "Chapter 056:01 Electricity Sector Reform Act",
            "Chapter 056:03 Hydro-Electric Power Act",
            "Chapter 056:04 Guyana Energy Agency Act",
            "Chapter 057:01 Public Utilities Commission Act",
            "Chapter 059:01 Lands Department Act",
            "Chapter 059:02 Geological Survey Act",
            "Chapter 059:03 Amerindian Lands Commission Act",
            "Chapter 059:04 Surveys (Special Provisions) Act",
            "Chapter 059:05 Guyana Lands and Surveys Commission Act",
            "Chapter 060:01 Immovable Property (Sale of Interests) Acts",
            "Chapter 060:02 Title to Land (Prescription and Limitation) Act",
            "Chapter 060:03 District Lands Partition and Re-Allotment Act",
            "Chapter 060:04 District Lands Partition and Re-Allotment (Special Procedure) Act",
            "Chapter 060:05 War Graves Act",
            "Chapter 061:01 Landlord and Tenant Act",
            "Chapter 061:02 Registration of Landlords Act",
            "Chapter 062:01 State Lands Act",
            "Chapter 062:02 State Lands Resumption Act",
            "Chapter 062:03 Public Lands (Private Roads) Act",
            "Chapter 062:04 State Grants (President's Signature) Act",
            "Chapter 062:05 Acquisition of Lands for Public Purposes Act",
            "Chapter 062:06 Acquisition of Land (Land Settlement) Act",
            "Chapter 062:07 Land Bonds Act",
            "Chapter 062:08 Vesting of Property (Acquisition by Purchase) Act",
            "Chapter 062:09 Acquisition of Lands (Not Beneficially Occupied) Act",
            "Chapter 063:01 Maritime Zones Act",
            "Chapter 064:01 Sea Defences Act",
            "Chapter 064:02 Sea Defence Act",
            "Chapter 064:03 Drainage and Irrigation Act",
            "Chapter 064:04 Drainage and Irrigation ( Declaration of Areas) Act",
            "Chapter 065:01 Mining Act",
            "Chapter 065:02 Bauxite Agreements (Adaption and Modification of Laws) Act",
            "Chapter 065:03 Blasting Operations Act",
            "Chapter 065:04 Petroleum (Exploration and Production) Act",
            "Chapter 065:05 Petroleum (Production) Act",
            "Chapter 065:06 Bauxite Nationalisation Act",
            "Chapter 065:07 Minerals Act",
            "Chapter 065:08 Miners Assistance Act",
            "Chapter 066:01 Guyana Gold Board Act",
            "Chapter 066:02 Guyana Geology and Mines Commission Act",
            "Chapter 066:02 Guyana Geology and Mines Commission Act",
            "Chapter 067:02 Guyana Forestry Commission Act",
            "Chapter 067:03 Guyana Timber Export Act",
            "Chapter 067:04 Timbering Marketing Act",
            "Chapter 068:02 National Agricultural Research Institute of Guyana Act",
            "Chapter 068:03 Plant Protection Act",
            "Chapter 068:04 Crops and Livestock Registration Act",
            "Chapter 068:05 Public Gardens and Agricultural Shows Act",
            "Chapter 068:06 Agricultural Loans Act",
            "Chapter 068:07 Plantation (Proprietors) Government Loans Act",
            "Chapter 068:08 Produce Protection Act",
            "Chapter 068:09 Pesticides and Toxic Chemicals Control Act",
            "Chapter 069:01 Guyana Rice Producers Association Act",
            "Chapter 069:02 Rice Farmers (Security of Tenure) Act",
            "Chapter 069:03 Sugar Industry Special Funds Act",
            "Chapter 069:04 National Cane Farming Committee Act",
            "Chapter 069:05 Coconut Products (Control) Act",
            "Chapter 069:06 Tobacco Impregnation Act",
            "Chapter 069:07 Balata Act",
            "Chapter 069:08 Sugar Industry Special Funds (Special Provisions) Act",
            "Chapter 069:09 Cane Farmers Special Funds Act",
            "Chapter 070:01 Mahaica-Mahaicony-Abary Agricultural Development Authority Act",
            "Chapter 071:01 Livestock Improvement Act",
            "Chapter 071:03 Animals (Control of Experiments) Act",
            "Chapter 071:04 Pounds Act",
            "Chapter 071:05 Dogs Act",
            "Chapter 071:06 Importation of Bees Act",
            "Chapter 071:07 Wild Birds Protection Act",
            "Chapter 071:08 Fisheries Act",
            "Chapter 071:09 Slaughter of Cattle (Control) Act",
            "Chapter 071:10 Guyana Livestock Development Authority Act",
            "Chapter 072:01 Guyana Rice Development Board Act",
            "Chapter 073:01 Audit Act",
            "Chapter 073:02 Fiscal Management and Accountability Act",
            "Chapter 073:03 Investment Act",
            "Chapter 073:04 Securities Industry Act",
            "Chapter 073:05 Procurement Act",
            "Chapter 073:06 Public Procurement Commission Tribunal Act",
            "Chapter 074:01 General Loan and Stock Act",
            "Chapter 074:02 Public General Loan (Supplementary) Act",
            "Chapter 074:03 Public Loans and Treasury Bills Act",
            "Chapter 074:04 General Local Loan Act",
            "Chapter 074:05 Treasury Savings Certificates and Savings Bond Act",
            "Chapter 074:06 General Loans (International Bank) Act",
            "Chapter 074:07 Livestock (Loans for Development) Act",
            "Chapter 074:08 External Loans Act",
            "Chapter 074:09 Debentures (Special Provisions) Act",
            "Chapter 074:10 Inter-American Development Bank Act",
            "Chapter 074:11 Premium Bonds Act",
            "Chapter 074:12 Inter-American Investment Corporation Act",
            "Chapter 074:13 Public Loan Act",
            "Chapter 075:01 Co-operative Financial Institutions Act",
            "Chapter 076:01 International Financial Organisation Act",
            "Chapter 077:01 Guarantee of Loans (Public Corporations and Companies) Act",
            "Chapter 077:02 Caribbean Investment Corporation Act",
            "Chapter 077:03 State Enterprises (Guarantee) Act",
            "Chapter 077:04 Caribbean Investment Fund Act",
            "Chapter 077:05 Bureau of Statistics Act",
            "Chapter 078:01 National Defence Bonds Act",
            "Chapter 078:02 State Planning Commission Act",
            "Chapter 079:01 Revenue Protection Act",
            "Chapter 079:02 Licence Revenue Act",
            "Chapter 079:03 Provisional Collection of Taxes Act",
            "Chapter 079:04 Revenue Authority Act",
            "Chapter 080:01 Tax Act",
            "Chapter 080:03 Stamp Duties (Management) Act",
            "Chapter 080:04 Miscellaneous Licences Act",
            "Chapter 080:05 Rice (CESS) Act",
            "Chapter 080:06 Entertainments Duty Act",
            "Chapter 080:07 Government Lotteries Act",
            "Chapter 080:08 Sale of Travel Tickets Act",
            "Chapter 081:01 Income Tax Act",
            "Chapter 081:02 Income Tax (In Aid of Industry) Act",
            "Chapter 081:03 Corporation Tax Act",
            "Chapter 081:05 Value-Added Tax Act",
            "Chapter 081:20 Capital Gains Act",
            "Chapter 081:21 Property Tax Act",
            "Chapter 081:22 Acreage Tax Act",
            "Chapter 081:24 Estate Duty (Deaths on Service) Act",
            "Chapter 082:01 Customs Act",
            "Chapter 082:03 Excise Tax Act",
            "Chapter 082:21 Intoxicating Liquor Licensing Act",
            "Chapter 082:22 Licensed Premises Act",
            "Chapter 082:23 Bitters and Cordials Act",
            "Chapter 082:24 Spirits Act",
            "Chapter 082:25 Stills Act",
            "Chapter 082:26 Members' Clubs Act",
            "Chapter 083:02 Bauxite (Production Levy) Act",
            "Chapter 084:01 Credit Reporting Act",
            "Chapter 085:02 Bank of Guyana Act",
            "Chapter 085:03 Financial Institutions Act",
            "Chapter 085:04 Caribbean Development Bank Agreement Act",
            "Chapter 085:05 Savings Schemes Act",
            "Chapter 085:06 Off-Shore Banking Act",
            "Chapter 085:08 Corporations (Provision for Conversion into Public Companies) Act",
            "Chapter 085:09 Banking Laws Act",
            "Chapter 085:10 Money Transfer Agencies (Licensing) Act",
            "Chapter 086:01 Foreign Exchange (Miscellaneous Provisions) Act",
            "Chapter 087:01 Dealers in Foreign Currency (Licensing) Act",
            "Chapter 088:01 Co-operative Societies Act",
            "Chapter 088:02 Industrial and Provident Societies Act",
            "Chapter 089:01 Companies Act",
            "Chapter 089:02 Partnership Act",
            "Chapter 089:03 Georgetown Chamber of Commerce and Industry Act",
            "Chapter 090:01 Trade Marks Act",
            "Chapter 090:03 Patents and Designs Act",
            "Chapter 090:04 Merchandise Marks Act",
            "Chapter 090:05 Business Names (Registration) Act",
            "Chapter 090:07 Competition and Fair Trading Act",
            "Chapter 090:10 Sale of Goods Act",
            "Chapter 090:11 Pledge of Goods Act",
            "Chapter 090:12 Bills of Sale Act",
            "Chapter 090:13 Bills of Exchange Act",
            "Chapter 090:15 Weights and Measures Act",
            "Chapter 090:16 Guyana National Bureau of Standards Act",
            "Chapter 091:01 Trade Act",
            "Chapter 091:02 Insurance Act",
            "Chapter 091:03 Traders (Breach of Contract) Act",
            "Chapter 091:04 Shops (Consolidation) Act",
            "Chapter 091:05 Money Lenders Act",
            "Chapter 091:06 Hucksters Licensing and Control Act",
            "Chapter 091:07 Acutioneers Act",
            "Chapter 091:08 Old Metal Dealers Act",
            "Chapter 091:09 Pawnbroking Act",
            "Chapter 091:11 Guyana Export Promotion Council Act",
            "Chapter 091:12 Export and Import (Special Provisions) Act",
            "Chapter 091:13 Guyana Tourism Authority Act",
            "Chapter 092:01 Petroleum Act",
            "Chapter 092:02 Sulphuric Acid Act",
            "Chapter 092:03 Molasses Act",
            "Chapter 095:01 Industries Aid and Encouragement Act",
            "Chapter 095:02 Factories (Hours and Holidays) Act",
            "Chapter 095:03 Factories (Dangerous Trades Regulation) Act",
            "Chapter 095:04 Steam Boilers Regulation Act",
            "Chapter 095:05 Rice Factories Act",
            "Chapter 095:06 Soap Act",
            "Chapter 096:01 Termination of Employment and Severance Pay Act",
            "Chapter 097:01 Land Surveyors Act",
            "Chapter 097:02 Weighers and Gaugers Act",
            "Chapter 097:03 Institute of Chartered Accountants of Guyana Act",
            "Chapter 098:01 Labour Act",
            "Chapter 098:03 Trade Unions Act",
            "Chapter 098:04 Wages Councils Act",
            "Chapter 098:05 Employment Exchanges Act",
            "Chapter 098:06 Recruiting of Workers Act",
            "Chapter 098:07 Trade Union Recognition Act",
            "Chapter 099:01 Employment of Young Persons and Children Act",
            "Chapter 099:02 Leave with Pay Act",
            "Chapter 099:03 Labour (Conditions of Employment of Certain Workers) Act",
            "Chapter 099:04 Housing of Labour Workers on Sugar Estates Act",
            "Chapter 099:05 Accidental Death and Personal Injuries (Damages) Act",
            "Chapter 099:06 Occupational Safety and Health Act",
            "Chapter 099:07 Bakeries (Hours of Work) Act",
            "Chapter 099:08 Prevention of Discrimination Act",
            "Chapter 099:10 Household Service Workers (Hours of Work) Act",
            "Cybercrime Act No. 16 of 2018"
        ];

        const fullPdfFiles = [
            "001.pdf", "002.pdf", "003.pdf", "004.pdf", "005.pdf", "006.pdf", "007.pdf", "008.pdf", "009.pdf", "010.pdf",
            "011.pdf", "012.pdf", "013.pdf", "014.pdf", "015.pdf", "016.pdf", "017.pdf", "018.pdf", "019.pdf", "020.pdf",
            "021.pdf", "022.pdf", "023.pdf", "024.pdf", "025.pdf", "026.pdf", "027.pdf", "028.pdf", "029.pdf", "030.pdf",
            "031.pdf", "032.pdf", "033.pdf", "034.pdf", "035.pdf", "036.pdf", "037.pdf", "038.pdf", "039.pdf", "040.pdf",
            "041.pdf", "042.pdf", "043.pdf", "044.pdf", "045.pdf", "046.pdf", "047.pdf", "048.pdf", "049.pdf", "050.pdf",
            "051.pdf", "052.pdf", "053.pdf", "054.pdf", "055.pdf", "056.pdf", "057.pdf", "058.pdf", "059.pdf", "060.pdf",
            "061.pdf", "062.pdf", "063.pdf", "064.pdf", "065.pdf", "066.pdf", "067.pdf", "068.pdf", "069.pdf", "070.pdf",
            "071.pdf", "072.pdf", "073.pdf", "074.pdf", "075.pdf", "076.pdf", "077.pdf", "078.pdf", "079.pdf", "080.pdf",
            "081.pdf", "082.pdf", "083.pdf", "084.pdf", "085.pdf", "086.pdf", "087.pdf", "088.pdf", "089.pdf", "090.pdf",
            "091.pdf", "092.pdf", "093.pdf", "094.pdf", "095.pdf", "096.pdf", "097.pdf", "098.pdf", "099.pdf", "100.pdf",
            "101.pdf", "102.pdf", "103.pdf", "104.pdf", "105.pdf", "106.pdf", "107.pdf", "108.pdf", "109.pdf", "110.pdf",
            "111.pdf", "112.pdf", "113.pdf", "114.pdf", "115.pdf", "116.pdf", "117.pdf", "118.pdf", "119.pdf", "120.pdf",
            "121.pdf", "122.pdf", "123.pdf", "124.pdf", "125.pdf", "126.pdf", "127.pdf", "128.pdf", "129.pdf", "130.pdf",
            "131.pdf", "132.pdf", "133.pdf", "134.pdf", "135.pdf", "136.pdf", "137.pdf", "138.pdf", "139.pdf", "140.pdf",
            "141.pdf", "142.pdf", "143.pdf", "144.pdf", "145.pdf", "146.pdf", "147.pdf", "148.pdf", "149.pdf", "150.pdf",
            "151.pdf", "152.pdf", "153.pdf", "154.pdf", "155.pdf", "156.pdf", "157.pdf", "158.pdf", "159.pdf", "160.pdf",
            "161.pdf", "162.pdf", "163.pdf", "164.pdf", "165.pdf", "166.pdf", "167.pdf", "168.pdf", "169.pdf", "170.pdf",
            "171.pdf", "172.pdf", "173.pdf", "174.pdf", "175.pdf", "176.pdf", "177.pdf", "178.pdf", "179.pdf", "180.pdf",
            "181.pdf", "182.pdf", "183.pdf", "184.pdf", "185.pdf", "186.pdf", "187.pdf", "188.pdf", "189.pdf", "190.pdf",
            "191.pdf", "192.pdf", "193.pdf", "194.pdf", "195.pdf", "196.pdf", "197.pdf", "198.pdf", "199.pdf", "200.pdf",
            "201.pdf", "202.pdf", "203.pdf", "204.pdf", "205.pdf", "206.pdf", "207.pdf", "208.pdf", "209.pdf", "210.pdf",
            "211.pdf", "212.pdf", "213.pdf", "214.pdf", "215.pdf", "216.pdf", "217.pdf", "218.pdf", "219.pdf", "220.pdf",
            "221.pdf", "222.pdf", "223.pdf", "224.pdf", "225.pdf", "226.pdf", "227.pdf", "228.pdf", "229.pdf", "230.pdf",
            "231.pdf", "232.pdf", "233.pdf", "234.pdf", "235.pdf", "236.pdf", "237.pdf", "238.pdf", "239.pdf", "240.pdf",
            "241.pdf", "242.pdf", "243.pdf", "244.pdf", "245.pdf", "246.pdf", "247.pdf", "248.pdf", "249.pdf", "250.pdf",
            "251.pdf", "252.pdf", "253.pdf", "254.pdf", "255.pdf", "256.pdf", "257.pdf", "258.pdf", "259.pdf", "260.pdf",
            "261.pdf", "262.pdf", "263.pdf", "264.pdf", "265.pdf", "266.pdf", "267.pdf", "268.pdf", "269.pdf", "270.pdf",
            "271.pdf", "272.pdf", "273.pdf", "274.pdf", "275.pdf", "276.pdf", "277.pdf", "278.pdf", "279.pdf", "280.pdf",
            "281.pdf", "282.pdf", "283.pdf", "284.pdf", "285.pdf", "286.pdf", "287.pdf", "288.pdf", "289.pdf", "290.pdf",
            "291.pdf", "292.pdf", "293.pdf", "294.pdf", "295.pdf", "296.pdf", "297.pdf", "298.pdf", "299.pdf", "300.pdf",
            "301.pdf", "302.pdf", "303.pdf", "304.pdf", "305.pdf", "306.pdf", "307.pdf", "308.pdf", "309.pdf", "310.pdf",
            "311.pdf", "312.pdf", "313.pdf", "314.pdf", "315.pdf", "316.pdf", "317.pdf", "318.pdf", "319.pdf", "320.pdf",
            "321.pdf", "322.pdf", "323.pdf", "324.pdf", "325.pdf", "326.pdf", "327.pdf", "328.pdf", "329.pdf", "330.pdf",
            "331.pdf", "332.pdf", "333.pdf", "334.pdf", "335.pdf", "336.pdf", "337.pdf", "338.pdf", "339.pdf", "340.pdf",
            "341.pdf", "342.pdf", "343.pdf", "344.pdf", "345.pdf", "346.pdf", "347.pdf", "348.pdf", "349.pdf", "350.pdf",
            "351.pdf", "352.pdf", "353.pdf", "354.pdf", "355.pdf", "356.pdf", "357.pdf", "358.pdf", "359.pdf", "360.pdf",
            "361.pdf", "362.pdf", "363.pdf", "364.pdf", "365.pdf", "366.pdf", "367.pdf", "368.pdf", "369.pdf", "370.pdf",
            "371.pdf", "372.pdf", "373.pdf", "374.pdf", "375.pdf", "376.pdf", "377.pdf", "378.pdf", "379.pdf", "380.pdf",
            "381.pdf", "382.pdf", "383.pdf", "384.pdf", "385.pdf", "386.pdf", "387.pdf", "388.pdf", "389.pdf", "390.pdf",
            "391.pdf", "392.pdf", "393.pdf", "394.pdf", "395.pdf", "396.pdf", "397.pdf", "398.pdf", "399.pdf", "400.pdf",
            "401.pdf", "402.pdf", "403.pdf", "404.pdf", "405.pdf", "406.pdf", "407.pdf", "408.pdf", "409.pdf", "410.pdf",
            "411.pdf", "412.pdf", "413.pdf", "414.pdf", "415.pdf", "416.pdf", "417.pdf", "418.pdf", "419.pdf", "420.pdf",
            "421.pdf", "422.pdf", "423.pdf", "424.pdf", "425.pdf", "426.pdf", "427.pdf", "428.pdf", "429.pdf", "430.pdf",
            "431.pdf", "432.pdf", "433.pdf", "434.pdf", "435.pdf", "436.pdf", "437.pdf", "438.pdf", "439.pdf", "440.pdf",
            "441.pdf", "442.pdf", "443.pdf", "444.pdf", "445.pdf", "446.pdf", "447.pdf", "448.pdf", "449.pdf", "450.pdf",
            "451.pdf", "452.pdf", "453.pdf", "454.pdf", "455.pdf", "456.pdf", "457.pdf", "458.pdf", "459.pdf", "460.pdf",
            "461.pdf", "462.pdf", "463.pdf"
        ];

        const searchHeader = document.getElementById('searchHeader');
        const searchInput = document.getElementById('searchInput');
        const listContainer = document.getElementById('listContainer');
        const listScroll = document.getElementById('listScroll');
        const pdfViewer = document.getElementById('pdfViewer');
        const pdfFrame = document.getElementById('pdfFrame');
        const pdfTitleSpan = document.getElementById('pdfTitle').querySelector('span');
        const backBar = document.getElementById('backBar');
        const backButton = document.getElementById('backButton');
        const noResults = document.getElementById('noResults');
        const itemCountSpan = document.getElementById('itemCount');

        function getReadOnlyPdfPath(filename) {
            const basePath = 'pdf/' + filename;
            return basePath + '#toolbar=0&navpanes=0&scrollbar=0&statusbar=0&messages=0&view=FitH';
        }

        function renderList(filterText = '') {
            const searchLower = filterText.trim().toLowerCase();
            const filteredIndices = [];

            for (let i = 0; i < fullPdfList.length; i++) {
                const chapter = fullPdfList[i];
                if (searchLower === '' || chapter.toLowerCase().includes(searchLower)) {
                    filteredIndices.push(i);
                }
            }

            itemCountSpan.textContent = `${filteredIndices.length} chapter${filteredIndices.length !== 1 ? 's' : ''}`;

            listScroll.innerHTML = '';

            if (filteredIndices.length === 0) {
                noResults.style.display = 'block';
            } else {
                noResults.style.display = 'none';
                const fragment = document.createDocumentFragment();
                filteredIndices.forEach(idx => {
                    const chapterName = fullPdfList[idx];
                    const pdfFile = fullPdfFiles[idx];
                    const div = document.createElement('div');
                    div.className = 'law-item';
                    div.setAttribute('data-pdf', pdfFile);
                    div.setAttribute('data-title', chapterName);
                    div.innerHTML = `<i class="fas fa-file-pdf"></i> ${chapterName}`;
                    div.addEventListener('click', () => openPdf(pdfFile, chapterName));
                    fragment.appendChild(div);
                });
                listScroll.appendChild(fragment);
            }
        }

        function openPdf(pdfBaseName, chapterTitle) {
            const fullPath = getReadOnlyPdfPath(pdfBaseName);
            pdfFrame.src = fullPath;
            pdfTitleSpan.textContent = chapterTitle;

            listContainer.style.display = 'none';
            searchHeader.classList.add('hidden');  
            pdfViewer.classList.add('visible');
            backBar.classList.add('visible');
        }

        function goBackToList() {
            pdfFrame.src = 'about:blank';
            pdfViewer.classList.remove('visible');
            listContainer.style.display = 'flex';
            searchHeader.classList.remove('hidden'); 
            backBar.classList.remove('visible');
        }

        function filterList() {
            renderList(searchInput.value);
        }

        function init() {
            renderList('');
            searchInput.addEventListener('input', filterList);
            backButton.addEventListener('click', goBackToList);

            window.addEventListener('keydown', (e) => {
                if (e.key === 'Escape' && pdfViewer.classList.contains('visible')) {
                    goBackToList();
                }
            });

            window.addEventListener('popstate', function() {
                if (pdfViewer.classList.contains('visible')) {
                    goBackToList();
                }
            });

            if (history.state === undefined) {
                history.pushState({ page: 'list' }, '');
            }

            window.onpopstate = function() {
                if (pdfViewer.classList.contains('visible')) {
                    goBackToList();
                    history.pushState({ page: 'list' }, '');
                }
            };
        }

        init();
    })();